---
apiVersion: v1
kind: Service
metadata:
  name: evite-micro-crypto
  namespace: evite-micro
  labels:
    app: evite-micro-crypto
    service: evite-micro-crypto
spec:
  ports:
    - port: 9090
      name: grpc
  selector:
    app: evite-micro-crypto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evite-micro-crypto
  namespace: evite-micro
  labels:
    app: evite-micro-crypto
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evite-micro-crypto
      version: v1
  template:
    metadata:
      labels:
        app: evite-micro-crypto
        version: v1
    spec:
      containers:
        - name: evite-micro-crypto
          image: registry.gitlab.com/mernxl-evite/evite-micro-crypto:latest
          imagePullPolicy: Always
          env:
            - name: CRYPTO_SYSTEM_SECRET
              valueFrom:
                  configMapKeyRef:
                    name: evite-config
                    key: CRYPTO_SYSTEM_SECRET
            - name: MONGODB_USER_NAME
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_USER_NAME
            - name: MONGODB_USER_PASS
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_USER_PASS
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MONGODB_URL
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_ENDPOINT
            - name: MINIO_REGION
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_REGION
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_PORT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: evite-config
                  key: MINIO_SECRET_KEY

            - name: SERVER_HOST
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "9090"
            - name: NODE_ENV
              value: production
            - name: GRPC_VERBOSITY
              value: DEBUG
            - name: GRPC_TRACE
              value: all
            - name: SMTP_USER_PASS
              value: ""
            - name: SMTP_USER_NAME
              value: ""
          ports:
            - containerPort: 9090
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evite-micro-crypto
  namespace: evite-micro
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evite-micro-crypto
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
